version: "3.9"

services:



  oracle2:
    image: gvenzl/oracle-xe:18-slim
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 123456
      APP_USER: useroracle
      APP_USER_PASSWORD: 123456
    volumes:
      - oracle-volume:/opt/oracle/oradata
    networks:
      - default

volumes:
  oracle-volume:

networks:
  default:
    driver: bridge